/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Voucher } from './Voucher';
import {
    VoucherFromJSON,
    VoucherFromJSONTyped,
    VoucherToJSON,
    VoucherToJSONTyped,
} from './Voucher';

/**
 * 
 * @export
 * @interface CheckVoucherDTO
 */
export interface CheckVoucherDTO {
    /**
     * 
     * @type {boolean}
     * @memberof CheckVoucherDTO
     */
    valid?: boolean;
    /**
     * 
     * @type {Voucher}
     * @memberof CheckVoucherDTO
     */
    voucher?: Voucher;
}

/**
 * Check if a given object implements the CheckVoucherDTO interface.
 */
export function instanceOfCheckVoucherDTO(value: object): value is CheckVoucherDTO {
    return true;
}

export function CheckVoucherDTOFromJSON(json: any): CheckVoucherDTO {
    return CheckVoucherDTOFromJSONTyped(json, false);
}

export function CheckVoucherDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckVoucherDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'valid': json['valid'] == null ? undefined : json['valid'],
        'voucher': json['voucher'] == null ? undefined : VoucherFromJSON(json['voucher']),
    };
}

export function CheckVoucherDTOToJSON(json: any): CheckVoucherDTO {
    return CheckVoucherDTOToJSONTyped(json, false);
}

export function CheckVoucherDTOToJSONTyped(value?: CheckVoucherDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valid': value['valid'],
        'voucher': VoucherToJSON(value['voucher']),
    };
}

