/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Transaksi } from './Transaksi';
import {
    TransaksiFromJSON,
    TransaksiFromJSONTyped,
    TransaksiToJSON,
    TransaksiToJSONTyped,
} from './Transaksi';

/**
 * 
 * @export
 * @interface DashboardDataDTO
 */
export interface DashboardDataDTO {
    /**
     * 
     * @type {number}
     * @memberof DashboardDataDTO
     */
    availableMotorCount?: number;
    /**
     * 
     * @type {number}
     * @memberof DashboardDataDTO
     */
    filedMotorCount?: number;
    /**
     * 
     * @type {number}
     * @memberof DashboardDataDTO
     */
    transaksiOngoing?: number;
    /**
     * 
     * @type {number}
     * @memberof DashboardDataDTO
     */
    totalIncome?: number;
    /**
     * 
     * @type {Array<Transaksi>}
     * @memberof DashboardDataDTO
     */
    chartTransaksi?: Array<Transaksi> | null;
}

/**
 * Check if a given object implements the DashboardDataDTO interface.
 */
export function instanceOfDashboardDataDTO(value: object): value is DashboardDataDTO {
    return true;
}

export function DashboardDataDTOFromJSON(json: any): DashboardDataDTO {
    return DashboardDataDTOFromJSONTyped(json, false);
}

export function DashboardDataDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardDataDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'availableMotorCount': json['availableMotorCount'] == null ? undefined : json['availableMotorCount'],
        'filedMotorCount': json['filedMotorCount'] == null ? undefined : json['filedMotorCount'],
        'transaksiOngoing': json['transaksiOngoing'] == null ? undefined : json['transaksiOngoing'],
        'totalIncome': json['totalIncome'] == null ? undefined : json['totalIncome'],
        'chartTransaksi': json['chartTransaksi'] == null ? undefined : ((json['chartTransaksi'] as Array<any>).map(TransaksiFromJSON)),
    };
}

export function DashboardDataDTOToJSON(json: any): DashboardDataDTO {
    return DashboardDataDTOToJSONTyped(json, false);
}

export function DashboardDataDTOToJSONTyped(value?: DashboardDataDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'availableMotorCount': value['availableMotorCount'],
        'filedMotorCount': value['filedMotorCount'],
        'transaksiOngoing': value['transaksiOngoing'],
        'totalIncome': value['totalIncome'],
        'chartTransaksi': value['chartTransaksi'] == null ? undefined : ((value['chartTransaksi'] as Array<any>).map(TransaksiToJSON)),
    };
}

