/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pengguna } from './Pengguna';
import {
    PenggunaFromJSON,
    PenggunaFromJSONTyped,
    PenggunaToJSON,
    PenggunaToJSONTyped,
} from './Pengguna';

/**
 * 
 * @export
 * @interface DeviceToken
 */
export interface DeviceToken {
    /**
     * 
     * @type {number}
     * @memberof DeviceToken
     */
    idToken?: number;
    /**
     * 
     * @type {string}
     * @memberof DeviceToken
     */
    idPengguna?: string | null;
    /**
     * 
     * @type {Pengguna}
     * @memberof DeviceToken
     */
    pengguna?: Pengguna;
    /**
     * 
     * @type {string}
     * @memberof DeviceToken
     */
    token?: string | null;
}

/**
 * Check if a given object implements the DeviceToken interface.
 */
export function instanceOfDeviceToken(value: object): value is DeviceToken {
    return true;
}

export function DeviceTokenFromJSON(json: any): DeviceToken {
    return DeviceTokenFromJSONTyped(json, false);
}

export function DeviceTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceToken {
    if (json == null) {
        return json;
    }
    return {
        
        'idToken': json['idToken'] == null ? undefined : json['idToken'],
        'idPengguna': json['idPengguna'] == null ? undefined : json['idPengguna'],
        'pengguna': json['pengguna'] == null ? undefined : PenggunaFromJSON(json['pengguna']),
        'token': json['token'] == null ? undefined : json['token'],
    };
}

  export function DeviceTokenToJSON(json: any): DeviceToken {
      return DeviceTokenToJSONTyped(json, false);
  }

  export function DeviceTokenToJSONTyped(value?: DeviceToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idToken': value['idToken'],
        'idPengguna': value['idPengguna'],
        'pengguna': PenggunaToJSON(value['pengguna']),
        'token': value['token'],
    };
}

