/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TargetNavigasi } from './TargetNavigasi';
import {
    TargetNavigasiFromJSON,
    TargetNavigasiFromJSONTyped,
    TargetNavigasiToJSON,
    TargetNavigasiToJSONTyped,
} from './TargetNavigasi';

/**
 * 
 * @export
 * @interface GetNotifikasDTO
 */
export interface GetNotifikasDTO {
    /**
     * 
     * @type {number}
     * @memberof GetNotifikasDTO
     */
    idNotifikasi?: number;
    /**
     * 
     * @type {string}
     * @memberof GetNotifikasDTO
     */
    idPengguna?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetNotifikasDTO
     */
    judul?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetNotifikasDTO
     */
    deskripsi?: string | null;
    /**
     * 
     * @type {TargetNavigasi}
     * @memberof GetNotifikasDTO
     */
    navigasi?: TargetNavigasi;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof GetNotifikasDTO
     */
    dataNavigasi?: { [key: string]: string; } | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetNotifikasDTO
     */
    isRead?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof GetNotifikasDTO
     */
    waktuNotifikasi?: Date;
}



/**
 * Check if a given object implements the GetNotifikasDTO interface.
 */
export function instanceOfGetNotifikasDTO(value: object): value is GetNotifikasDTO {
    return true;
}

export function GetNotifikasDTOFromJSON(json: any): GetNotifikasDTO {
    return GetNotifikasDTOFromJSONTyped(json, false);
}

export function GetNotifikasDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNotifikasDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'idNotifikasi': json['idNotifikasi'] == null ? undefined : json['idNotifikasi'],
        'idPengguna': json['idPengguna'] == null ? undefined : json['idPengguna'],
        'judul': json['judul'] == null ? undefined : json['judul'],
        'deskripsi': json['deskripsi'] == null ? undefined : json['deskripsi'],
        'navigasi': json['navigasi'] == null ? undefined : TargetNavigasiFromJSON(json['navigasi']),
        'dataNavigasi': json['dataNavigasi'] == null ? undefined : json['dataNavigasi'],
        'isRead': json['isRead'] == null ? undefined : json['isRead'],
        'waktuNotifikasi': json['waktuNotifikasi'] == null ? undefined : (new Date(json['waktuNotifikasi'])),
    };
}

  export function GetNotifikasDTOToJSON(json: any): GetNotifikasDTO {
      return GetNotifikasDTOToJSONTyped(json, false);
  }

  export function GetNotifikasDTOToJSONTyped(value?: GetNotifikasDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idNotifikasi': value['idNotifikasi'],
        'idPengguna': value['idPengguna'],
        'judul': value['judul'],
        'deskripsi': value['deskripsi'],
        'navigasi': TargetNavigasiToJSON(value['navigasi']),
        'dataNavigasi': value['dataNavigasi'],
        'isRead': value['isRead'],
        'waktuNotifikasi': value['waktuNotifikasi'] == null ? undefined : ((value['waktuNotifikasi']).toISOString()),
    };
}

