/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MetodePembayaran = {
    TransferBank: 'TransferBank',
    KartuKredit: 'KartuKredit',
    DompetDigital: 'DompetDigital',
    Tunai: 'Tunai'
} as const;
export type MetodePembayaran = typeof MetodePembayaran[keyof typeof MetodePembayaran];


export function instanceOfMetodePembayaran(value: any): boolean {
    for (const key in MetodePembayaran) {
        if (Object.prototype.hasOwnProperty.call(MetodePembayaran, key)) {
            if (MetodePembayaran[key as keyof typeof MetodePembayaran] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MetodePembayaranFromJSON(json: any): MetodePembayaran {
    return MetodePembayaranFromJSONTyped(json, false);
}

export function MetodePembayaranFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetodePembayaran {
    return json as MetodePembayaran;
}

export function MetodePembayaranToJSON(value?: MetodePembayaran | null): any {
    return value as any;
}

export function MetodePembayaranToJSONTyped(value: any, ignoreDiscriminator: boolean): MetodePembayaran {
    return value as MetodePembayaran;
}

