/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Mitra } from './Mitra';
import {
    MitraFromJSON,
    MitraFromJSONTyped,
    MitraToJSON,
    MitraToJSONTyped,
} from './Mitra';

/**
 * 
 * @export
 * @interface MitraMotorDTO
 */
export interface MitraMotorDTO {
    /**
     * 
     * @type {Mitra}
     * @memberof MitraMotorDTO
     */
    mitra?: Mitra;
    /**
     * 
     * @type {number}
     * @memberof MitraMotorDTO
     */
    jumlahMotor?: number;
}

/**
 * Check if a given object implements the MitraMotorDTO interface.
 */
export function instanceOfMitraMotorDTO(value: object): value is MitraMotorDTO {
    return true;
}

export function MitraMotorDTOFromJSON(json: any): MitraMotorDTO {
    return MitraMotorDTOFromJSONTyped(json, false);
}

export function MitraMotorDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MitraMotorDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'mitra': json['mitra'] == null ? undefined : MitraFromJSON(json['mitra']),
        'jumlahMotor': json['jumlahMotor'] == null ? undefined : json['jumlahMotor'],
    };
}

export function MitraMotorDTOToJSON(json: any): MitraMotorDTO {
    return MitraMotorDTOToJSONTyped(json, false);
}

export function MitraMotorDTOToJSONTyped(value?: MitraMotorDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mitra': MitraToJSON(value['mitra']),
        'jumlahMotor': value['jumlahMotor'],
    };
}

