/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Mitra } from './Mitra';
import {
    MitraFromJSON,
    MitraFromJSONTyped,
    MitraToJSON,
    MitraToJSONTyped,
} from './Mitra';
import type { MotorImage } from './MotorImage';
import {
    MotorImageFromJSON,
    MotorImageFromJSONTyped,
    MotorImageToJSON,
    MotorImageToJSONTyped,
} from './MotorImage';
import type { Diskon } from './Diskon';
import {
    DiskonFromJSON,
    DiskonFromJSONTyped,
    DiskonToJSON,
    DiskonToJSONTyped,
} from './Diskon';

/**
 * 
 * @export
 * @interface Motor
 */
export interface Motor {
    /**
     * 
     * @type {number}
     * @memberof Motor
     */
    idMotor?: number;
    /**
     * 
     * @type {string}
     * @memberof Motor
     */
    platNomor?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Motor
     */
    idMitra?: number;
    /**
     * 
     * @type {string}
     * @memberof Motor
     */
    nomorSTNK?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Motor
     */
    nomorBPKB?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Motor
     */
    model?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Motor
     */
    brand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Motor
     */
    tipe?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Motor
     */
    tahun?: number;
    /**
     * 
     * @type {string}
     * @memberof Motor
     */
    transmisi?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Motor
     */
    statusMotor?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Motor
     */
    hargaHarian?: number;
    /**
     * 
     * @type {Array<Diskon>}
     * @memberof Motor
     */
    diskon?: Array<Diskon> | null;
    /**
     * 
     * @type {number}
     * @memberof Motor
     */
    idMotorImage?: number | null;
    /**
     * 
     * @type {Mitra}
     * @memberof Motor
     */
    mitra?: Mitra;
    /**
     * 
     * @type {MotorImage}
     * @memberof Motor
     */
    motorImage?: MotorImage;
}

/**
 * Check if a given object implements the Motor interface.
 */
export function instanceOfMotor(value: object): value is Motor {
    return true;
}

export function MotorFromJSON(json: any): Motor {
    return MotorFromJSONTyped(json, false);
}

export function MotorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Motor {
    if (json == null) {
        return json;
    }
    return {
        
        'idMotor': json['idMotor'] == null ? undefined : json['idMotor'],
        'platNomor': json['platNomor'] == null ? undefined : json['platNomor'],
        'idMitra': json['idMitra'] == null ? undefined : json['idMitra'],
        'nomorSTNK': json['nomorSTNK'] == null ? undefined : json['nomorSTNK'],
        'nomorBPKB': json['nomorBPKB'] == null ? undefined : json['nomorBPKB'],
        'model': json['model'] == null ? undefined : json['model'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'tipe': json['tipe'] == null ? undefined : json['tipe'],
        'tahun': json['tahun'] == null ? undefined : json['tahun'],
        'transmisi': json['transmisi'] == null ? undefined : json['transmisi'],
        'statusMotor': json['statusMotor'] == null ? undefined : json['statusMotor'],
        'hargaHarian': json['hargaHarian'] == null ? undefined : json['hargaHarian'],
        'diskon': json['diskon'] == null ? undefined : ((json['diskon'] as Array<any>).map(DiskonFromJSON)),
        'idMotorImage': json['idMotorImage'] == null ? undefined : json['idMotorImage'],
        'mitra': json['mitra'] == null ? undefined : MitraFromJSON(json['mitra']),
        'motorImage': json['motorImage'] == null ? undefined : MotorImageFromJSON(json['motorImage']),
    };
}

export function MotorToJSON(json: any): Motor {
    return MotorToJSONTyped(json, false);
}

export function MotorToJSONTyped(value?: Motor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idMotor': value['idMotor'],
        'platNomor': value['platNomor'],
        'idMitra': value['idMitra'],
        'nomorSTNK': value['nomorSTNK'],
        'nomorBPKB': value['nomorBPKB'],
        'model': value['model'],
        'brand': value['brand'],
        'tipe': value['tipe'],
        'tahun': value['tahun'],
        'transmisi': value['transmisi'],
        'statusMotor': value['statusMotor'],
        'hargaHarian': value['hargaHarian'],
        'diskon': value['diskon'] == null ? undefined : ((value['diskon'] as Array<any>).map(DiskonToJSON)),
        'idMotorImage': value['idMotorImage'],
        'mitra': MitraToJSON(value['mitra']),
        'motorImage': MotorImageToJSON(value['motorImage']),
    };
}

