/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransmisiMotor } from './TransmisiMotor';
import {
    TransmisiMotorFromJSON,
    TransmisiMotorFromJSONTyped,
    TransmisiMotorToJSON,
    TransmisiMotorToJSONTyped,
} from './TransmisiMotor';
import type { StatusMotor } from './StatusMotor';
import {
    StatusMotorFromJSON,
    StatusMotorFromJSONTyped,
    StatusMotorToJSON,
    StatusMotorToJSONTyped,
} from './StatusMotor';

/**
 * 
 * @export
 * @interface MotorForm
 */
export interface MotorForm {
    /**
     * 
     * @type {string}
     * @memberof MotorForm
     */
    platNomor: string;
    /**
     * 
     * @type {number}
     * @memberof MotorForm
     */
    idMitra: number;
    /**
     * 
     * @type {string}
     * @memberof MotorForm
     */
    nomorSTNK: string;
    /**
     * 
     * @type {string}
     * @memberof MotorForm
     */
    nomorBPKB: string;
    /**
     * 
     * @type {string}
     * @memberof MotorForm
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof MotorForm
     */
    brand: string;
    /**
     * 
     * @type {string}
     * @memberof MotorForm
     */
    tipe: string;
    /**
     * 
     * @type {number}
     * @memberof MotorForm
     */
    tahun: number;
    /**
     * 
     * @type {TransmisiMotor}
     * @memberof MotorForm
     */
    transmisi: TransmisiMotor;
    /**
     * 
     * @type {StatusMotor}
     * @memberof MotorForm
     */
    statusMotor: StatusMotor;
    /**
     * 
     * @type {number}
     * @memberof MotorForm
     */
    hargaHarian: number;
}



/**
 * Check if a given object implements the MotorForm interface.
 */
export function instanceOfMotorForm(value: object): value is MotorForm {
    if (!('platNomor' in value) || value['platNomor'] === undefined) return false;
    if (!('idMitra' in value) || value['idMitra'] === undefined) return false;
    if (!('nomorSTNK' in value) || value['nomorSTNK'] === undefined) return false;
    if (!('nomorBPKB' in value) || value['nomorBPKB'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('brand' in value) || value['brand'] === undefined) return false;
    if (!('tipe' in value) || value['tipe'] === undefined) return false;
    if (!('tahun' in value) || value['tahun'] === undefined) return false;
    if (!('transmisi' in value) || value['transmisi'] === undefined) return false;
    if (!('statusMotor' in value) || value['statusMotor'] === undefined) return false;
    if (!('hargaHarian' in value) || value['hargaHarian'] === undefined) return false;
    return true;
}

export function MotorFormFromJSON(json: any): MotorForm {
    return MotorFormFromJSONTyped(json, false);
}

export function MotorFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): MotorForm {
    if (json == null) {
        return json;
    }
    return {
        
        'platNomor': json['platNomor'],
        'idMitra': json['idMitra'],
        'nomorSTNK': json['nomorSTNK'],
        'nomorBPKB': json['nomorBPKB'],
        'model': json['model'],
        'brand': json['brand'],
        'tipe': json['tipe'],
        'tahun': json['tahun'],
        'transmisi': TransmisiMotorFromJSON(json['transmisi']),
        'statusMotor': StatusMotorFromJSON(json['statusMotor']),
        'hargaHarian': json['hargaHarian'],
    };
}

export function MotorFormToJSON(json: any): MotorForm {
    return MotorFormToJSONTyped(json, false);
}

export function MotorFormToJSONTyped(value?: MotorForm | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platNomor': value['platNomor'],
        'idMitra': value['idMitra'],
        'nomorSTNK': value['nomorSTNK'],
        'nomorBPKB': value['nomorBPKB'],
        'model': value['model'],
        'brand': value['brand'],
        'tipe': value['tipe'],
        'tahun': value['tahun'],
        'transmisi': TransmisiMotorToJSON(value['transmisi']),
        'statusMotor': StatusMotorToJSON(value['statusMotor']),
        'hargaHarian': value['hargaHarian'],
    };
}

