/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Motor } from './Motor';
import {
    MotorFromJSON,
    MotorFromJSONTyped,
    MotorToJSON,
    MotorToJSONTyped,
} from './Motor';
import type { Pengguna } from './Pengguna';
import {
    PenggunaFromJSON,
    PenggunaFromJSONTyped,
    PenggunaToJSON,
    PenggunaToJSONTyped,
} from './Pengguna';

/**
 * 
 * @export
 * @interface MotorTableDTO
 */
export interface MotorTableDTO {
    /**
     * 
     * @type {Motor}
     * @memberof MotorTableDTO
     */
    motor?: Motor;
    /**
     * 
     * @type {Pengguna}
     * @memberof MotorTableDTO
     */
    ownerPengguna?: Pengguna;
}

/**
 * Check if a given object implements the MotorTableDTO interface.
 */
export function instanceOfMotorTableDTO(value: object): value is MotorTableDTO {
    return true;
}

export function MotorTableDTOFromJSON(json: any): MotorTableDTO {
    return MotorTableDTOFromJSONTyped(json, false);
}

export function MotorTableDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MotorTableDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'motor': json['motor'] == null ? undefined : MotorFromJSON(json['motor']),
        'ownerPengguna': json['ownerPengguna'] == null ? undefined : PenggunaFromJSON(json['ownerPengguna']),
    };
}

export function MotorTableDTOToJSON(json: any): MotorTableDTO {
    return MotorTableDTOToJSONTyped(json, false);
}

export function MotorTableDTOToJSONTyped(value?: MotorTableDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'motor': MotorToJSON(value['motor']),
        'ownerPengguna': PenggunaToJSON(value['ownerPengguna']),
    };
}

