/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MotorSorting = {
    None: 'None',
    MostPopular: 'MostPopular',
    BestDiscount: 'BestDiscount',
    BestRating: 'BestRating'
} as const;
export type MotorSorting = typeof MotorSorting[keyof typeof MotorSorting];


export function instanceOfMotorSorting(value: any): boolean {
    for (const key in MotorSorting) {
        if (Object.prototype.hasOwnProperty.call(MotorSorting, key)) {
            if (MotorSorting[key as keyof typeof MotorSorting] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MotorSortingFromJSON(json: any): MotorSorting {
    return MotorSortingFromJSONTyped(json, false);
}

export function MotorSortingFromJSONTyped(json: any, ignoreDiscriminator: boolean): MotorSorting {
    return json as MotorSorting;
}

export function MotorSortingToJSON(value?: MotorSorting | null): any {
    return value as any;
}

export function MotorSortingToJSONTyped(value: any, ignoreDiscriminator: boolean): MotorSorting {
    return value as MotorSorting;
}

