/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TargetNavigasi } from './TargetNavigasi';
import {
    TargetNavigasiFromJSON,
    TargetNavigasiFromJSONTyped,
    TargetNavigasiToJSON,
    TargetNavigasiToJSONTyped,
} from './TargetNavigasi';
import type { Pengguna } from './Pengguna';
import {
    PenggunaFromJSON,
    PenggunaFromJSONTyped,
    PenggunaToJSON,
    PenggunaToJSONTyped,
} from './Pengguna';

/**
 * 
 * @export
 * @interface Notifikasi
 */
export interface Notifikasi {
    /**
     * 
     * @type {number}
     * @memberof Notifikasi
     */
    idNotifikasi?: number;
    /**
     * 
     * @type {string}
     * @memberof Notifikasi
     */
    idPengguna?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Notifikasi
     */
    judul?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Notifikasi
     */
    deskripsi?: string | null;
    /**
     * 
     * @type {TargetNavigasi}
     * @memberof Notifikasi
     */
    navigasi?: TargetNavigasi;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Notifikasi
     */
    dataNavigasi?: { [key: string]: string; } | null;
    /**
     * 
     * @type {boolean}
     * @memberof Notifikasi
     */
    isRead?: boolean;
    /**
     * 
     * @type {Pengguna}
     * @memberof Notifikasi
     */
    pengguna?: Pengguna;
}



/**
 * Check if a given object implements the Notifikasi interface.
 */
export function instanceOfNotifikasi(value: object): value is Notifikasi {
    return true;
}

export function NotifikasiFromJSON(json: any): Notifikasi {
    return NotifikasiFromJSONTyped(json, false);
}

export function NotifikasiFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notifikasi {
    if (json == null) {
        return json;
    }
    return {
        
        'idNotifikasi': json['idNotifikasi'] == null ? undefined : json['idNotifikasi'],
        'idPengguna': json['idPengguna'] == null ? undefined : json['idPengguna'],
        'judul': json['judul'] == null ? undefined : json['judul'],
        'deskripsi': json['deskripsi'] == null ? undefined : json['deskripsi'],
        'navigasi': json['navigasi'] == null ? undefined : TargetNavigasiFromJSON(json['navigasi']),
        'dataNavigasi': json['dataNavigasi'] == null ? undefined : json['dataNavigasi'],
        'isRead': json['isRead'] == null ? undefined : json['isRead'],
        'pengguna': json['pengguna'] == null ? undefined : PenggunaFromJSON(json['pengguna']),
    };
}

export function NotifikasiToJSON(json: any): Notifikasi {
    return NotifikasiToJSONTyped(json, false);
}

export function NotifikasiToJSONTyped(value?: Notifikasi | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idNotifikasi': value['idNotifikasi'],
        'idPengguna': value['idPengguna'],
        'judul': value['judul'],
        'deskripsi': value['deskripsi'],
        'navigasi': TargetNavigasiToJSON(value['navigasi']),
        'dataNavigasi': value['dataNavigasi'],
        'isRead': value['isRead'],
        'pengguna': PenggunaToJSON(value['pengguna']),
    };
}

