/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pengguna } from './Pengguna';
import {
    PenggunaFromJSON,
    PenggunaFromJSONTyped,
    PenggunaToJSON,
    PenggunaToJSONTyped,
} from './Pengguna';
import type { Voucher } from './Voucher';
import {
    VoucherFromJSON,
    VoucherFromJSONTyped,
    VoucherToJSON,
    VoucherToJSONTyped,
} from './Voucher';

/**
 * 
 * @export
 * @interface Pelanggan
 */
export interface Pelanggan {
    /**
     * 
     * @type {number}
     * @memberof Pelanggan
     */
    idPelanggan?: number;
    /**
     * 
     * @type {string}
     * @memberof Pelanggan
     */
    idPengguna?: string | null;
    /**
     * 
     * @type {Pengguna}
     * @memberof Pelanggan
     */
    pengguna?: Pengguna;
    /**
     * 
     * @type {string}
     * @memberof Pelanggan
     */
    nomorSIM?: string | null;
    /**
     * 
     * @type {Array<Voucher>}
     * @memberof Pelanggan
     */
    usedVouchers?: Array<Voucher> | null;
}

/**
 * Check if a given object implements the Pelanggan interface.
 */
export function instanceOfPelanggan(value: object): value is Pelanggan {
    return true;
}

export function PelangganFromJSON(json: any): Pelanggan {
    return PelangganFromJSONTyped(json, false);
}

export function PelangganFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pelanggan {
    if (json == null) {
        return json;
    }
    return {
        
        'idPelanggan': json['idPelanggan'] == null ? undefined : json['idPelanggan'],
        'idPengguna': json['idPengguna'] == null ? undefined : json['idPengguna'],
        'pengguna': json['pengguna'] == null ? undefined : PenggunaFromJSON(json['pengguna']),
        'nomorSIM': json['nomorSIM'] == null ? undefined : json['nomorSIM'],
        'usedVouchers': json['usedVouchers'] == null ? undefined : ((json['usedVouchers'] as Array<any>).map(VoucherFromJSON)),
    };
}

export function PelangganToJSON(json: any): Pelanggan {
    return PelangganToJSONTyped(json, false);
}

export function PelangganToJSONTyped(value?: Pelanggan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idPelanggan': value['idPelanggan'],
        'idPengguna': value['idPengguna'],
        'pengguna': PenggunaToJSON(value['pengguna']),
        'nomorSIM': value['nomorSIM'],
        'usedVouchers': value['usedVouchers'] == null ? undefined : ((value['usedVouchers'] as Array<any>).map(VoucherToJSON)),
    };
}

