/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Transaksi } from './Transaksi';
import {
    TransaksiFromJSON,
    TransaksiFromJSONTyped,
    TransaksiToJSON,
    TransaksiToJSONTyped,
} from './Transaksi';

/**
 * 
 * @export
 * @interface Pembayaran
 */
export interface Pembayaran {
    /**
     * 
     * @type {number}
     * @memberof Pembayaran
     */
    idPembayaran?: number;
    /**
     * 
     * @type {number}
     * @memberof Pembayaran
     */
    idTransaksi?: number;
    /**
     * 
     * @type {string}
     * @memberof Pembayaran
     */
    metodePembayaran?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Pembayaran
     */
    statusPembayaran?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Pembayaran
     */
    tanggalPembayaran?: Date | null;
    /**
     * 
     * @type {Transaksi}
     * @memberof Pembayaran
     */
    transaksi?: Transaksi;
}

/**
 * Check if a given object implements the Pembayaran interface.
 */
export function instanceOfPembayaran(value: object): value is Pembayaran {
    return true;
}

export function PembayaranFromJSON(json: any): Pembayaran {
    return PembayaranFromJSONTyped(json, false);
}

export function PembayaranFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pembayaran {
    if (json == null) {
        return json;
    }
    return {
        
        'idPembayaran': json['idPembayaran'] == null ? undefined : json['idPembayaran'],
        'idTransaksi': json['idTransaksi'] == null ? undefined : json['idTransaksi'],
        'metodePembayaran': json['metodePembayaran'] == null ? undefined : json['metodePembayaran'],
        'statusPembayaran': json['statusPembayaran'] == null ? undefined : json['statusPembayaran'],
        'tanggalPembayaran': json['tanggalPembayaran'] == null ? undefined : (new Date(json['tanggalPembayaran'])),
        'transaksi': json['transaksi'] == null ? undefined : TransaksiFromJSON(json['transaksi']),
    };
}

export function PembayaranToJSON(json: any): Pembayaran {
    return PembayaranToJSONTyped(json, false);
}

export function PembayaranToJSONTyped(value?: Pembayaran | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idPembayaran': value['idPembayaran'],
        'idTransaksi': value['idTransaksi'],
        'metodePembayaran': value['metodePembayaran'],
        'statusPembayaran': value['statusPembayaran'],
        'tanggalPembayaran': value['tanggalPembayaran'] == null ? undefined : ((value['tanggalPembayaran'] as any).toISOString()),
        'transaksi': TransaksiToJSON(value['transaksi']),
    };
}

