/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeviceToken } from './DeviceToken';
import {
    DeviceTokenFromJSON,
    DeviceTokenFromJSONTyped,
    DeviceTokenToJSON,
    DeviceTokenToJSONTyped,
} from './DeviceToken';
import type { Notifikasi } from './Notifikasi';
import {
    NotifikasiFromJSON,
    NotifikasiFromJSONTyped,
    NotifikasiToJSON,
    NotifikasiToJSONTyped,
} from './Notifikasi';
import type { Pelanggan } from './Pelanggan';
import {
    PelangganFromJSON,
    PelangganFromJSONTyped,
    PelangganToJSON,
    PelangganToJSONTyped,
} from './Pelanggan';

/**
 * 
 * @export
 * @interface Pengguna
 */
export interface Pengguna {
    /**
     * 
     * @type {string}
     * @memberof Pengguna
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Pengguna
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Pengguna
     */
    normalizedUserName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Pengguna
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Pengguna
     */
    normalizedEmail?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Pengguna
     */
    emailConfirmed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Pengguna
     */
    passwordHash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Pengguna
     */
    securityStamp?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Pengguna
     */
    concurrencyStamp?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Pengguna
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Pengguna
     */
    phoneNumberConfirmed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Pengguna
     */
    twoFactorEnabled?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Pengguna
     */
    lockoutEnd?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof Pengguna
     */
    lockoutEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Pengguna
     */
    accessFailedCount?: number;
    /**
     * 
     * @type {Pelanggan}
     * @memberof Pengguna
     */
    pelanggan?: Pelanggan;
    /**
     * 
     * @type {Array<Notifikasi>}
     * @memberof Pengguna
     */
    notifikasis?: Array<Notifikasi> | null;
    /**
     * 
     * @type {Array<DeviceToken>}
     * @memberof Pengguna
     */
    deviceTokens?: Array<DeviceToken> | null;
    /**
     * 
     * @type {string}
     * @memberof Pengguna
     */
    nama?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Pengguna
     */
    tanggalLahir?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Pengguna
     */
    nomorTelepon?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Pengguna
     */
    umur?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Pengguna
     */
    nomorKTP?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Pengguna
     */
    alamat?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Pengguna
     */
    idGambar?: number | null;
}

/**
 * Check if a given object implements the Pengguna interface.
 */
export function instanceOfPengguna(value: object): value is Pengguna {
    return true;
}

export function PenggunaFromJSON(json: any): Pengguna {
    return PenggunaFromJSONTyped(json, false);
}

export function PenggunaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pengguna {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'normalizedUserName': json['normalizedUserName'] == null ? undefined : json['normalizedUserName'],
        'email': json['email'] == null ? undefined : json['email'],
        'normalizedEmail': json['normalizedEmail'] == null ? undefined : json['normalizedEmail'],
        'emailConfirmed': json['emailConfirmed'] == null ? undefined : json['emailConfirmed'],
        'passwordHash': json['passwordHash'] == null ? undefined : json['passwordHash'],
        'securityStamp': json['securityStamp'] == null ? undefined : json['securityStamp'],
        'concurrencyStamp': json['concurrencyStamp'] == null ? undefined : json['concurrencyStamp'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'phoneNumberConfirmed': json['phoneNumberConfirmed'] == null ? undefined : json['phoneNumberConfirmed'],
        'twoFactorEnabled': json['twoFactorEnabled'] == null ? undefined : json['twoFactorEnabled'],
        'lockoutEnd': json['lockoutEnd'] == null ? undefined : (new Date(json['lockoutEnd'])),
        'lockoutEnabled': json['lockoutEnabled'] == null ? undefined : json['lockoutEnabled'],
        'accessFailedCount': json['accessFailedCount'] == null ? undefined : json['accessFailedCount'],
        'pelanggan': json['pelanggan'] == null ? undefined : PelangganFromJSON(json['pelanggan']),
        'notifikasis': json['notifikasis'] == null ? undefined : ((json['notifikasis'] as Array<any>).map(NotifikasiFromJSON)),
        'deviceTokens': json['deviceTokens'] == null ? undefined : ((json['deviceTokens'] as Array<any>).map(DeviceTokenFromJSON)),
        'nama': json['nama'] == null ? undefined : json['nama'],
        'tanggalLahir': json['tanggalLahir'] == null ? undefined : (new Date(json['tanggalLahir'])),
        'nomorTelepon': json['nomorTelepon'] == null ? undefined : json['nomorTelepon'],
        'umur': json['umur'] == null ? undefined : json['umur'],
        'nomorKTP': json['nomorKTP'] == null ? undefined : json['nomorKTP'],
        'alamat': json['alamat'] == null ? undefined : json['alamat'],
        'idGambar': json['idGambar'] == null ? undefined : json['idGambar'],
    };
}

export function PenggunaToJSON(json: any): Pengguna {
    return PenggunaToJSONTyped(json, false);
}

export function PenggunaToJSONTyped(value?: Pengguna | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userName': value['userName'],
        'normalizedUserName': value['normalizedUserName'],
        'email': value['email'],
        'normalizedEmail': value['normalizedEmail'],
        'emailConfirmed': value['emailConfirmed'],
        'passwordHash': value['passwordHash'],
        'securityStamp': value['securityStamp'],
        'concurrencyStamp': value['concurrencyStamp'],
        'phoneNumber': value['phoneNumber'],
        'phoneNumberConfirmed': value['phoneNumberConfirmed'],
        'twoFactorEnabled': value['twoFactorEnabled'],
        'lockoutEnd': value['lockoutEnd'] == null ? undefined : ((value['lockoutEnd'] as any).toISOString()),
        'lockoutEnabled': value['lockoutEnabled'],
        'accessFailedCount': value['accessFailedCount'],
        'pelanggan': PelangganToJSON(value['pelanggan']),
        'notifikasis': value['notifikasis'] == null ? undefined : ((value['notifikasis'] as Array<any>).map(NotifikasiToJSON)),
        'deviceTokens': value['deviceTokens'] == null ? undefined : ((value['deviceTokens'] as Array<any>).map(DeviceTokenToJSON)),
        'nama': value['nama'],
        'tanggalLahir': value['tanggalLahir'] == null ? undefined : ((value['tanggalLahir'] as any).toISOString()),
        'nomorTelepon': value['nomorTelepon'],
        'umur': value['umur'],
        'nomorKTP': value['nomorKTP'],
        'alamat': value['alamat'],
        'idGambar': value['idGambar'],
    };
}

