/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusDiskon } from './StatusDiskon';
import {
    StatusDiskonFromJSON,
    StatusDiskonFromJSONTyped,
    StatusDiskonToJSON,
    StatusDiskonToJSONTyped,
} from './StatusDiskon';

/**
 * 
 * @export
 * @interface PostDiskonDTO
 */
export interface PostDiskonDTO {
    /**
     * 
     * @type {number}
     * @memberof PostDiskonDTO
     */
    idMotor?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PostDiskonDTO
     */
    nama?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostDiskonDTO
     */
    deskripsi?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PostDiskonDTO
     */
    jumlahDiskon?: number | null;
    /**
     * 
     * @type {StatusDiskon}
     * @memberof PostDiskonDTO
     */
    statusDiskon?: StatusDiskon;
    /**
     * 
     * @type {Date}
     * @memberof PostDiskonDTO
     */
    tanggalMulai?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PostDiskonDTO
     */
    tanggalAkhir?: Date | null;
}



/**
 * Check if a given object implements the PostDiskonDTO interface.
 */
export function instanceOfPostDiskonDTO(value: object): value is PostDiskonDTO {
    return true;
}

export function PostDiskonDTOFromJSON(json: any): PostDiskonDTO {
    return PostDiskonDTOFromJSONTyped(json, false);
}

export function PostDiskonDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDiskonDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'idMotor': json['idMotor'] == null ? undefined : json['idMotor'],
        'nama': json['nama'] == null ? undefined : json['nama'],
        'deskripsi': json['deskripsi'] == null ? undefined : json['deskripsi'],
        'jumlahDiskon': json['jumlahDiskon'] == null ? undefined : json['jumlahDiskon'],
        'statusDiskon': json['statusDiskon'] == null ? undefined : StatusDiskonFromJSON(json['statusDiskon']),
        'tanggalMulai': json['tanggalMulai'] == null ? undefined : (new Date(json['tanggalMulai'])),
        'tanggalAkhir': json['tanggalAkhir'] == null ? undefined : (new Date(json['tanggalAkhir'])),
    };
}

export function PostDiskonDTOToJSON(json: any): PostDiskonDTO {
    return PostDiskonDTOToJSONTyped(json, false);
}

export function PostDiskonDTOToJSONTyped(value?: PostDiskonDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idMotor': value['idMotor'],
        'nama': value['nama'],
        'deskripsi': value['deskripsi'],
        'jumlahDiskon': value['jumlahDiskon'],
        'statusDiskon': StatusDiskonToJSON(value['statusDiskon']),
        'tanggalMulai': value['tanggalMulai'] == null ? undefined : ((value['tanggalMulai'] as any).toISOString()),
        'tanggalAkhir': value['tanggalAkhir'] == null ? undefined : ((value['tanggalAkhir'] as any).toISOString()),
    };
}

