/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusMitra } from './StatusMitra';
import {
    StatusMitraFromJSON,
    StatusMitraFromJSONTyped,
    StatusMitraToJSON,
    StatusMitraToJSONTyped,
} from './StatusMitra';

/**
 * 
 * @export
 * @interface PostMitraDTO
 */
export interface PostMitraDTO {
    /**
     * 
     * @type {number}
     * @memberof PostMitraDTO
     */
    idMitra?: number;
    /**
     * 
     * @type {StatusMitra}
     * @memberof PostMitraDTO
     */
    status?: StatusMitra;
}



/**
 * Check if a given object implements the PostMitraDTO interface.
 */
export function instanceOfPostMitraDTO(value: object): value is PostMitraDTO {
    return true;
}

export function PostMitraDTOFromJSON(json: any): PostMitraDTO {
    return PostMitraDTOFromJSONTyped(json, false);
}

export function PostMitraDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostMitraDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'idMitra': json['idMitra'] == null ? undefined : json['idMitra'],
        'status': json['status'] == null ? undefined : StatusMitraFromJSON(json['status']),
    };
}

  export function PostMitraDTOToJSON(json: any): PostMitraDTO {
      return PostMitraDTOToJSONTyped(json, false);
  }

  export function PostMitraDTOToJSONTyped(value?: PostMitraDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idMitra': value['idMitra'],
        'status': StatusMitraToJSON(value['status']),
    };
}

