/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TargetNavigasi } from './TargetNavigasi';
import {
    TargetNavigasiFromJSON,
    TargetNavigasiFromJSONTyped,
    TargetNavigasiToJSON,
    TargetNavigasiToJSONTyped,
} from './TargetNavigasi';

/**
 * 
 * @export
 * @interface PostNotifikasDTO
 */
export interface PostNotifikasDTO {
    /**
     * 
     * @type {string}
     * @memberof PostNotifikasDTO
     */
    idPengguna?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostNotifikasDTO
     */
    judul?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostNotifikasDTO
     */
    deskripsi?: string | null;
    /**
     * 
     * @type {TargetNavigasi}
     * @memberof PostNotifikasDTO
     */
    navigasi?: TargetNavigasi;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PostNotifikasDTO
     */
    dataNavigasi?: { [key: string]: string; } | null;
    /**
     * 
     * @type {boolean}
     * @memberof PostNotifikasDTO
     */
    isRead?: boolean;
}



/**
 * Check if a given object implements the PostNotifikasDTO interface.
 */
export function instanceOfPostNotifikasDTO(value: object): value is PostNotifikasDTO {
    return true;
}

export function PostNotifikasDTOFromJSON(json: any): PostNotifikasDTO {
    return PostNotifikasDTOFromJSONTyped(json, false);
}

export function PostNotifikasDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostNotifikasDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'idPengguna': json['idPengguna'] == null ? undefined : json['idPengguna'],
        'judul': json['judul'] == null ? undefined : json['judul'],
        'deskripsi': json['deskripsi'] == null ? undefined : json['deskripsi'],
        'navigasi': json['navigasi'] == null ? undefined : TargetNavigasiFromJSON(json['navigasi']),
        'dataNavigasi': json['dataNavigasi'] == null ? undefined : json['dataNavigasi'],
        'isRead': json['isRead'] == null ? undefined : json['isRead'],
    };
}

export function PostNotifikasDTOToJSON(json: any): PostNotifikasDTO {
    return PostNotifikasDTOToJSONTyped(json, false);
}

export function PostNotifikasDTOToJSONTyped(value?: PostNotifikasDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idPengguna': value['idPengguna'],
        'judul': value['judul'],
        'deskripsi': value['deskripsi'],
        'navigasi': TargetNavigasiToJSON(value['navigasi']),
        'dataNavigasi': value['dataNavigasi'],
        'isRead': value['isRead'],
    };
}

