/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostUlasanDTO
 */
export interface PostUlasanDTO {
    /**
     * 
     * @type {number}
     * @memberof PostUlasanDTO
     */
    idMotor: number;
    /**
     * 
     * @type {number}
     * @memberof PostUlasanDTO
     */
    idPelanggan: number;
    /**
     * 
     * @type {number}
     * @memberof PostUlasanDTO
     */
    rating: number;
    /**
     * 
     * @type {string}
     * @memberof PostUlasanDTO
     */
    komentar: string;
}

/**
 * Check if a given object implements the PostUlasanDTO interface.
 */
export function instanceOfPostUlasanDTO(value: object): value is PostUlasanDTO {
    if (!('idMotor' in value) || value['idMotor'] === undefined) return false;
    if (!('idPelanggan' in value) || value['idPelanggan'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('komentar' in value) || value['komentar'] === undefined) return false;
    return true;
}

export function PostUlasanDTOFromJSON(json: any): PostUlasanDTO {
    return PostUlasanDTOFromJSONTyped(json, false);
}

export function PostUlasanDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostUlasanDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'idMotor': json['idMotor'],
        'idPelanggan': json['idPelanggan'],
        'rating': json['rating'],
        'komentar': json['komentar'],
    };
}

  export function PostUlasanDTOToJSON(json: any): PostUlasanDTO {
      return PostUlasanDTOToJSONTyped(json, false);
  }

  export function PostUlasanDTOToJSONTyped(value?: PostUlasanDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idMotor': value['idMotor'],
        'idPelanggan': value['idPelanggan'],
        'rating': value['rating'],
        'komentar': value['komentar'],
    };
}

