/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusMitra } from './StatusMitra';
import {
    StatusMitraFromJSON,
    StatusMitraFromJSONTyped,
    StatusMitraToJSON,
    StatusMitraToJSONTyped,
} from './StatusMitra';

/**
 * 
 * @export
 * @interface PostCreateMitraDTO
 */
export interface PostCreateMitraDTO {
    /**
     * 
     * @type {string}
     * @memberof PostCreateMitraDTO
     */
    idPengguna?: string | null;
    /**
     * 
     * @type {StatusMitra}
     * @memberof PostCreateMitraDTO
     */
    status?: StatusMitra;
}



/**
 * Check if a given object implements the PostCreateMitraDTO interface.
 */
export function instanceOfPostCreateMitraDTO(value: object): value is PostCreateMitraDTO {
    return true;
}

export function PostCreateMitraDTOFromJSON(json: any): PostCreateMitraDTO {
    return PostCreateMitraDTOFromJSONTyped(json, false);
}

export function PostCreateMitraDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCreateMitraDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'idPengguna': json['idPengguna'] == null ? undefined : json['idPengguna'],
        'status': json['status'] == null ? undefined : StatusMitraFromJSON(json['status']),
    };
}

export function PostCreateMitraDTOToJSON(json: any): PostCreateMitraDTO {
    return PostCreateMitraDTOToJSONTyped(json, false);
}

export function PostCreateMitraDTOToJSONTyped(value?: PostCreateMitraDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idPengguna': value['idPengguna'],
        'status': StatusMitraToJSON(value['status']),
    };
}

