/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPenggunaDTO
 */
export interface PostPenggunaDTO {
    /**
     * 
     * @type {string}
     * @memberof PostPenggunaDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PostPenggunaDTO
     */
    nama?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PostPenggunaDTO
     */
    tanggalLahir?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PostPenggunaDTO
     */
    nomorTelepon?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PostPenggunaDTO
     */
    umur?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PostPenggunaDTO
     */
    nomorKTP?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostPenggunaDTO
     */
    alamat?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostPenggunaDTO
     */
    idGambar?: string | null;
}

/**
 * Check if a given object implements the PostPenggunaDTO interface.
 */
export function instanceOfPostPenggunaDTO(value: object): value is PostPenggunaDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function PostPenggunaDTOFromJSON(json: any): PostPenggunaDTO {
    return PostPenggunaDTOFromJSONTyped(json, false);
}

export function PostPenggunaDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPenggunaDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nama': json['nama'] == null ? undefined : json['nama'],
        'tanggalLahir': json['tanggalLahir'] == null ? undefined : (new Date(json['tanggalLahir'])),
        'nomorTelepon': json['nomorTelepon'] == null ? undefined : json['nomorTelepon'],
        'umur': json['umur'] == null ? undefined : json['umur'],
        'nomorKTP': json['nomorKTP'] == null ? undefined : json['nomorKTP'],
        'alamat': json['alamat'] == null ? undefined : json['alamat'],
        'idGambar': json['idGambar'] == null ? undefined : json['idGambar'],
    };
}

export function PostPenggunaDTOToJSON(json: any): PostPenggunaDTO {
    return PostPenggunaDTOToJSONTyped(json, false);
}

export function PostPenggunaDTOToJSONTyped(value?: PostPenggunaDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nama': value['nama'],
        'tanggalLahir': value['tanggalLahir'] == null ? undefined : ((value['tanggalLahir'] as any).toISOString()),
        'nomorTelepon': value['nomorTelepon'],
        'umur': value['umur'],
        'nomorKTP': value['nomorKTP'],
        'alamat': value['alamat'],
        'idGambar': value['idGambar'],
    };
}

