/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusVoucher } from './StatusVoucher';
import {
    StatusVoucherFromJSON,
    StatusVoucherFromJSONTyped,
    StatusVoucherToJSON,
    StatusVoucherToJSONTyped,
} from './StatusVoucher';

/**
 * 
 * @export
 * @interface PostVoucherDTO
 */
export interface PostVoucherDTO {
    /**
     * 
     * @type {string}
     * @memberof PostVoucherDTO
     */
    namaVoucher: string;
    /**
     * 
     * @type {StatusVoucher}
     * @memberof PostVoucherDTO
     */
    statusVoucher: StatusVoucher;
    /**
     * 
     * @type {Date}
     * @memberof PostVoucherDTO
     */
    tanggalMulai: Date;
    /**
     * 
     * @type {Date}
     * @memberof PostVoucherDTO
     */
    tanggalAkhir: Date;
    /**
     * 
     * @type {number}
     * @memberof PostVoucherDTO
     */
    persenVoucher: number;
    /**
     * 
     * @type {string}
     * @memberof PostVoucherDTO
     */
    kodeVoucher: string;
}



/**
 * Check if a given object implements the PostVoucherDTO interface.
 */
export function instanceOfPostVoucherDTO(value: object): value is PostVoucherDTO {
    if (!('namaVoucher' in value) || value['namaVoucher'] === undefined) return false;
    if (!('statusVoucher' in value) || value['statusVoucher'] === undefined) return false;
    if (!('tanggalMulai' in value) || value['tanggalMulai'] === undefined) return false;
    if (!('tanggalAkhir' in value) || value['tanggalAkhir'] === undefined) return false;
    if (!('persenVoucher' in value) || value['persenVoucher'] === undefined) return false;
    if (!('kodeVoucher' in value) || value['kodeVoucher'] === undefined) return false;
    return true;
}

export function PostVoucherDTOFromJSON(json: any): PostVoucherDTO {
    return PostVoucherDTOFromJSONTyped(json, false);
}

export function PostVoucherDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostVoucherDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'namaVoucher': json['namaVoucher'],
        'statusVoucher': StatusVoucherFromJSON(json['statusVoucher']),
        'tanggalMulai': (new Date(json['tanggalMulai'])),
        'tanggalAkhir': (new Date(json['tanggalAkhir'])),
        'persenVoucher': json['persenVoucher'],
        'kodeVoucher': json['kodeVoucher'],
    };
}

  export function PostVoucherDTOToJSON(json: any): PostVoucherDTO {
      return PostVoucherDTOToJSONTyped(json, false);
  }

  export function PostVoucherDTOToJSONTyped(value?: PostVoucherDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'namaVoucher': value['namaVoucher'],
        'statusVoucher': StatusVoucherToJSON(value['statusVoucher']),
        'tanggalMulai': ((value['tanggalMulai']).toISOString()),
        'tanggalAkhir': ((value['tanggalAkhir']).toISOString()),
        'persenVoucher': value['persenVoucher'],
        'kodeVoucher': value['kodeVoucher'],
    };
}

