/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetodePembayaran } from './MetodePembayaran';
import {
    MetodePembayaranFromJSON,
    MetodePembayaranFromJSONTyped,
    MetodePembayaranToJSON,
    MetodePembayaranToJSONTyped,
} from './MetodePembayaran';

/**
 * 
 * @export
 * @interface PostPembayaranDTO
 */
export interface PostPembayaranDTO {
    /**
     * 
     * @type {number}
     * @memberof PostPembayaranDTO
     */
    idTransaksi: number;
    /**
     * 
     * @type {MetodePembayaran}
     * @memberof PostPembayaranDTO
     */
    metodePembayaran: MetodePembayaran;
}



/**
 * Check if a given object implements the PostPembayaranDTO interface.
 */
export function instanceOfPostPembayaranDTO(value: object): value is PostPembayaranDTO {
    if (!('idTransaksi' in value) || value['idTransaksi'] === undefined) return false;
    if (!('metodePembayaran' in value) || value['metodePembayaran'] === undefined) return false;
    return true;
}

export function PostPembayaranDTOFromJSON(json: any): PostPembayaranDTO {
    return PostPembayaranDTOFromJSONTyped(json, false);
}

export function PostPembayaranDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPembayaranDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'idTransaksi': json['idTransaksi'],
        'metodePembayaran': MetodePembayaranFromJSON(json['metodePembayaran']),
    };
}

export function PostPembayaranDTOToJSON(json: any): PostPembayaranDTO {
    return PostPembayaranDTOToJSONTyped(json, false);
}

export function PostPembayaranDTOToJSONTyped(value?: PostPembayaranDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idTransaksi': value['idTransaksi'],
        'metodePembayaran': MetodePembayaranToJSON(value['metodePembayaran']),
    };
}

