/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPelangganDTO
 */
export interface PostPelangganDTO {
    /**
     * 
     * @type {number}
     * @memberof PostPelangganDTO
     */
    idPelanggan: number;
    /**
     * 
     * @type {string}
     * @memberof PostPelangganDTO
     */
    nomorSIM?: string | null;
}

/**
 * Check if a given object implements the PostPelangganDTO interface.
 */
export function instanceOfPostPelangganDTO(value: object): value is PostPelangganDTO {
    if (!('idPelanggan' in value) || value['idPelanggan'] === undefined) return false;
    return true;
}

export function PostPelangganDTOFromJSON(json: any): PostPelangganDTO {
    return PostPelangganDTOFromJSONTyped(json, false);
}

export function PostPelangganDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPelangganDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'idPelanggan': json['idPelanggan'],
        'nomorSIM': json['nomorSIM'] == null ? undefined : json['nomorSIM'],
    };
}

  export function PostPelangganDTOToJSON(json: any): PostPelangganDTO {
      return PostPelangganDTOToJSONTyped(json, false);
  }

  export function PostPelangganDTOToJSONTyped(value?: PostPelangganDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idPelanggan': value['idPelanggan'],
        'nomorSIM': value['nomorSIM'],
    };
}

