/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutMotorDTO
 */
export interface PutMotorDTO {
    /**
     * 
     * @type {string}
     * @memberof PutMotorDTO
     */
    platNomor: string;
    /**
     * 
     * @type {string}
     * @memberof PutMotorDTO
     */
    nomorSTNK: string;
    /**
     * 
     * @type {string}
     * @memberof PutMotorDTO
     */
    nomorBPKB: string;
    /**
     * 
     * @type {string}
     * @memberof PutMotorDTO
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof PutMotorDTO
     */
    brand: string;
    /**
     * 
     * @type {string}
     * @memberof PutMotorDTO
     */
    tipe: string;
    /**
     * 
     * @type {number}
     * @memberof PutMotorDTO
     */
    tahun: number;
    /**
     * 
     * @type {string}
     * @memberof PutMotorDTO
     */
    transmisi: string;
    /**
     * 
     * @type {string}
     * @memberof PutMotorDTO
     */
    statusMotor: string;
    /**
     * 
     * @type {number}
     * @memberof PutMotorDTO
     */
    hargaHarian: number;
}

/**
 * Check if a given object implements the PutMotorDTO interface.
 */
export function instanceOfPutMotorDTO(value: object): value is PutMotorDTO {
    if (!('platNomor' in value) || value['platNomor'] === undefined) return false;
    if (!('nomorSTNK' in value) || value['nomorSTNK'] === undefined) return false;
    if (!('nomorBPKB' in value) || value['nomorBPKB'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('brand' in value) || value['brand'] === undefined) return false;
    if (!('tipe' in value) || value['tipe'] === undefined) return false;
    if (!('tahun' in value) || value['tahun'] === undefined) return false;
    if (!('transmisi' in value) || value['transmisi'] === undefined) return false;
    if (!('statusMotor' in value) || value['statusMotor'] === undefined) return false;
    if (!('hargaHarian' in value) || value['hargaHarian'] === undefined) return false;
    return true;
}

export function PutMotorDTOFromJSON(json: any): PutMotorDTO {
    return PutMotorDTOFromJSONTyped(json, false);
}

export function PutMotorDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutMotorDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'platNomor': json['platNomor'],
        'nomorSTNK': json['nomorSTNK'],
        'nomorBPKB': json['nomorBPKB'],
        'model': json['model'],
        'brand': json['brand'],
        'tipe': json['tipe'],
        'tahun': json['tahun'],
        'transmisi': json['transmisi'],
        'statusMotor': json['statusMotor'],
        'hargaHarian': json['hargaHarian'],
    };
}

export function PutMotorDTOToJSON(json: any): PutMotorDTO {
    return PutMotorDTOToJSONTyped(json, false);
}

export function PutMotorDTOToJSONTyped(value?: PutMotorDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platNomor': value['platNomor'],
        'nomorSTNK': value['nomorSTNK'],
        'nomorBPKB': value['nomorBPKB'],
        'model': value['model'],
        'brand': value['brand'],
        'tipe': value['tipe'],
        'tahun': value['tahun'],
        'transmisi': value['transmisi'],
        'statusMotor': value['statusMotor'],
        'hargaHarian': value['hargaHarian'],
    };
}

