/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutPembayaranDTO
 */
export interface PutPembayaranDTO {
    /**
     * 
     * @type {string}
     * @memberof PutPembayaranDTO
     */
    metodePembayaran?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PutPembayaranDTO
     */
    statusPembayaran?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PutPembayaranDTO
     */
    tanggalPembayaran?: Date | null;
}

/**
 * Check if a given object implements the PutPembayaranDTO interface.
 */
export function instanceOfPutPembayaranDTO(value: object): value is PutPembayaranDTO {
    return true;
}

export function PutPembayaranDTOFromJSON(json: any): PutPembayaranDTO {
    return PutPembayaranDTOFromJSONTyped(json, false);
}

export function PutPembayaranDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutPembayaranDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'metodePembayaran': json['metodePembayaran'] == null ? undefined : json['metodePembayaran'],
        'statusPembayaran': json['statusPembayaran'] == null ? undefined : json['statusPembayaran'],
        'tanggalPembayaran': json['tanggalPembayaran'] == null ? undefined : (new Date(json['tanggalPembayaran'])),
    };
}

  export function PutPembayaranDTOToJSON(json: any): PutPembayaranDTO {
      return PutPembayaranDTOToJSONTyped(json, false);
  }

  export function PutPembayaranDTOToJSONTyped(value?: PutPembayaranDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metodePembayaran': value['metodePembayaran'],
        'statusPembayaran': value['statusPembayaran'],
        'tanggalPembayaran': value['tanggalPembayaran'] == null ? undefined : ((value['tanggalPembayaran'] as any).toISOString()),
    };
}

