/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetodePembayaran } from './MetodePembayaran';
import {
    MetodePembayaranFromJSON,
    MetodePembayaranFromJSONTyped,
    MetodePembayaranToJSON,
    MetodePembayaranToJSONTyped,
} from './MetodePembayaran';
import type { StatusPembayaran } from './StatusPembayaran';
import {
    StatusPembayaranFromJSON,
    StatusPembayaranFromJSONTyped,
    StatusPembayaranToJSON,
    StatusPembayaranToJSONTyped,
} from './StatusPembayaran';

/**
 * 
 * @export
 * @interface PutPembayaranDTO
 */
export interface PutPembayaranDTO {
    /**
     * 
     * @type {MetodePembayaran}
     * @memberof PutPembayaranDTO
     */
    metodePembayaran?: MetodePembayaran;
    /**
     * 
     * @type {StatusPembayaran}
     * @memberof PutPembayaranDTO
     */
    statusPembayaran?: StatusPembayaran;
    /**
     * 
     * @type {Date}
     * @memberof PutPembayaranDTO
     */
    tanggalPembayaran?: Date | null;
}



/**
 * Check if a given object implements the PutPembayaranDTO interface.
 */
export function instanceOfPutPembayaranDTO(value: object): value is PutPembayaranDTO {
    return true;
}

export function PutPembayaranDTOFromJSON(json: any): PutPembayaranDTO {
    return PutPembayaranDTOFromJSONTyped(json, false);
}

export function PutPembayaranDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutPembayaranDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'metodePembayaran': json['metodePembayaran'] == null ? undefined : MetodePembayaranFromJSON(json['metodePembayaran']),
        'statusPembayaran': json['statusPembayaran'] == null ? undefined : StatusPembayaranFromJSON(json['statusPembayaran']),
        'tanggalPembayaran': json['tanggalPembayaran'] == null ? undefined : (new Date(json['tanggalPembayaran'])),
    };
}

export function PutPembayaranDTOToJSON(json: any): PutPembayaranDTO {
    return PutPembayaranDTOToJSONTyped(json, false);
}

export function PutPembayaranDTOToJSONTyped(value?: PutPembayaranDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metodePembayaran': MetodePembayaranToJSON(value['metodePembayaran']),
        'statusPembayaran': StatusPembayaranToJSON(value['statusPembayaran']),
        'tanggalPembayaran': value['tanggalPembayaran'] == null ? undefined : ((value['tanggalPembayaran'] as any).toISOString()),
    };
}

