/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterForm
 */
export interface RegisterForm {
    /**
     * 
     * @type {string}
     * @memberof RegisterForm
     */
    nama: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterForm
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterForm
     */
    password: string;
}

/**
 * Check if a given object implements the RegisterForm interface.
 */
export function instanceOfRegisterForm(value: object): value is RegisterForm {
    if (!('nama' in value) || value['nama'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function RegisterFormFromJSON(json: any): RegisterForm {
    return RegisterFormFromJSONTyped(json, false);
}

export function RegisterFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterForm {
    if (json == null) {
        return json;
    }
    return {
        
        'nama': json['nama'],
        'email': json['email'],
        'password': json['password'],
    };
}

  export function RegisterFormToJSON(json: any): RegisterForm {
      return RegisterFormToJSONTyped(json, false);
  }

  export function RegisterFormToJSONTyped(value?: RegisterForm | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nama': value['nama'],
        'email': value['email'],
        'password': value['password'],
    };
}

