/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StatusMitra = {
    Aktif: 'Aktif',
    NonAktif: 'NonAktif'
} as const;
export type StatusMitra = typeof StatusMitra[keyof typeof StatusMitra];


export function instanceOfStatusMitra(value: any): boolean {
    for (const key in StatusMitra) {
        if (Object.prototype.hasOwnProperty.call(StatusMitra, key)) {
            if (StatusMitra[key as keyof typeof StatusMitra] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StatusMitraFromJSON(json: any): StatusMitra {
    return StatusMitraFromJSONTyped(json, false);
}

export function StatusMitraFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusMitra {
    return json as StatusMitra;
}

export function StatusMitraToJSON(value?: StatusMitra | null): any {
    return value as any;
}

export function StatusMitraToJSONTyped(value: any, ignoreDiscriminator: boolean): StatusMitra {
    return value as StatusMitra;
}

