/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StatusVoucher = {
    Aktif: 'Aktif',
    NonAktif: 'NonAktif'
} as const;
export type StatusVoucher = typeof StatusVoucher[keyof typeof StatusVoucher];


export function instanceOfStatusVoucher(value: any): boolean {
    for (const key in StatusVoucher) {
        if (Object.prototype.hasOwnProperty.call(StatusVoucher, key)) {
            if (StatusVoucher[key as keyof typeof StatusVoucher] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StatusVoucherFromJSON(json: any): StatusVoucher {
    return StatusVoucherFromJSONTyped(json, false);
}

export function StatusVoucherFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusVoucher {
    return json as StatusVoucher;
}

export function StatusVoucherToJSON(value?: StatusVoucher | null): any {
    return value as any;
}

export function StatusVoucherToJSONTyped(value: any, ignoreDiscriminator: boolean): StatusVoucher {
    return value as StatusVoucher;
}

