/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StatusPembayaran = {
    BelumLunas: 'BelumLunas',
    MenungguKonfirmasi: 'MenungguKonfirmasi',
    Lunas: 'Lunas',
    Gagal: 'Gagal'
} as const;
export type StatusPembayaran = typeof StatusPembayaran[keyof typeof StatusPembayaran];


export function instanceOfStatusPembayaran(value: any): boolean {
    for (const key in StatusPembayaran) {
        if (Object.prototype.hasOwnProperty.call(StatusPembayaran, key)) {
            if (StatusPembayaran[key as keyof typeof StatusPembayaran] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StatusPembayaranFromJSON(json: any): StatusPembayaran {
    return StatusPembayaranFromJSONTyped(json, false);
}

export function StatusPembayaranFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusPembayaran {
    return json as StatusPembayaran;
}

export function StatusPembayaranToJSON(value?: StatusPembayaran | null): any {
    return value as any;
}

export function StatusPembayaranToJSONTyped(value: any, ignoreDiscriminator: boolean): StatusPembayaran {
    return value as StatusPembayaran;
}

