/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StatusMotor = {
    Diajukan: 'Diajukan',
    Tersedia: 'Tersedia',
    Disewa: 'Disewa',
    DalamPerbaikan: 'DalamPerbaikan',
    TidakTersedia: 'TidakTersedia'
} as const;
export type StatusMotor = typeof StatusMotor[keyof typeof StatusMotor];


export function instanceOfStatusMotor(value: any): boolean {
    for (const key in StatusMotor) {
        if (Object.prototype.hasOwnProperty.call(StatusMotor, key)) {
            if (StatusMotor[key as keyof typeof StatusMotor] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StatusMotorFromJSON(json: any): StatusMotor {
    return StatusMotorFromJSONTyped(json, false);
}

export function StatusMotorFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusMotor {
    return json as StatusMotor;
}

export function StatusMotorToJSON(value?: StatusMotor | null): any {
    return value as any;
}

export function StatusMotorToJSONTyped(value: any, ignoreDiscriminator: boolean): StatusMotor {
    return value as StatusMotor;
}

