/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StatusTransaksi = {
    Dibuat: 'Dibuat',
    Berlangsung: 'Berlangsung',
    Batal: 'Batal',
    Selesai: 'Selesai'
} as const;
export type StatusTransaksi = typeof StatusTransaksi[keyof typeof StatusTransaksi];


export function instanceOfStatusTransaksi(value: any): boolean {
    for (const key in StatusTransaksi) {
        if (Object.prototype.hasOwnProperty.call(StatusTransaksi, key)) {
            if (StatusTransaksi[key as keyof typeof StatusTransaksi] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StatusTransaksiFromJSON(json: any): StatusTransaksi {
    return StatusTransaksiFromJSONTyped(json, false);
}

export function StatusTransaksiFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusTransaksi {
    return json as StatusTransaksi;
}

export function StatusTransaksiToJSON(value?: StatusTransaksi | null): any {
    return value as any;
}

export function StatusTransaksiToJSONTyped(value: any, ignoreDiscriminator: boolean): StatusTransaksi {
    return value as StatusTransaksi;
}

