/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StatusDiskon = {
    Aktif: 'Aktif',
    NonAktif: 'NonAktif'
} as const;
export type StatusDiskon = typeof StatusDiskon[keyof typeof StatusDiskon];


export function instanceOfStatusDiskon(value: any): boolean {
    for (const key in StatusDiskon) {
        if (Object.prototype.hasOwnProperty.call(StatusDiskon, key)) {
            if (StatusDiskon[key as keyof typeof StatusDiskon] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StatusDiskonFromJSON(json: any): StatusDiskon {
    return StatusDiskonFromJSONTyped(json, false);
}

export function StatusDiskonFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusDiskon {
    return json as StatusDiskon;
}

export function StatusDiskonToJSON(value?: StatusDiskon | null): any {
    return value as any;
}

export function StatusDiskonToJSONTyped(value: any, ignoreDiscriminator: boolean): StatusDiskon {
    return value as StatusDiskon;
}

