/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TargetNavigasi = {
    None: 'None',
    Transaksi: 'Transaksi',
    EditProfile: 'EditProfile'
} as const;
export type TargetNavigasi = typeof TargetNavigasi[keyof typeof TargetNavigasi];


export function instanceOfTargetNavigasi(value: any): boolean {
    for (const key in TargetNavigasi) {
        if (Object.prototype.hasOwnProperty.call(TargetNavigasi, key)) {
            if (TargetNavigasi[key as keyof typeof TargetNavigasi] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TargetNavigasiFromJSON(json: any): TargetNavigasi {
    return TargetNavigasiFromJSONTyped(json, false);
}

export function TargetNavigasiFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetNavigasi {
    return json as TargetNavigasi;
}

export function TargetNavigasiToJSON(value?: TargetNavigasi | null): any {
    return value as any;
}

export function TargetNavigasiToJSONTyped(value: any, ignoreDiscriminator: boolean): TargetNavigasi {
    return value as TargetNavigasi;
}

