/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TransmisiMotor = {
    Matic: 'Matic',
    Manual: 'Manual'
} as const;
export type TransmisiMotor = typeof TransmisiMotor[keyof typeof TransmisiMotor];


export function instanceOfTransmisiMotor(value: any): boolean {
    for (const key in TransmisiMotor) {
        if (Object.prototype.hasOwnProperty.call(TransmisiMotor, key)) {
            if (TransmisiMotor[key as keyof typeof TransmisiMotor] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TransmisiMotorFromJSON(json: any): TransmisiMotor {
    return TransmisiMotorFromJSONTyped(json, false);
}

export function TransmisiMotorFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransmisiMotor {
    return json as TransmisiMotor;
}

export function TransmisiMotorToJSON(value?: TransmisiMotor | null): any {
    return value as any;
}

export function TransmisiMotorToJSONTyped(value: any, ignoreDiscriminator: boolean): TransmisiMotor {
    return value as TransmisiMotor;
}

