/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusVoucher } from './StatusVoucher';
import {
    StatusVoucherFromJSON,
    StatusVoucherFromJSONTyped,
    StatusVoucherToJSON,
    StatusVoucherToJSONTyped,
} from './StatusVoucher';
import type { Pelanggan } from './Pelanggan';
import {
    PelangganFromJSON,
    PelangganFromJSONTyped,
    PelangganToJSON,
    PelangganToJSONTyped,
} from './Pelanggan';

/**
 * 
 * @export
 * @interface Voucher
 */
export interface Voucher {
    /**
     * 
     * @type {number}
     * @memberof Voucher
     */
    idVoucher?: number;
    /**
     * 
     * @type {string}
     * @memberof Voucher
     */
    namaVoucher?: string | null;
    /**
     * 
     * @type {StatusVoucher}
     * @memberof Voucher
     */
    statusVoucher?: StatusVoucher;
    /**
     * 
     * @type {Date}
     * @memberof Voucher
     */
    tanggalMulai?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Voucher
     */
    tanggalAkhir?: Date;
    /**
     * 
     * @type {number}
     * @memberof Voucher
     */
    persenVoucher?: number;
    /**
     * 
     * @type {string}
     * @memberof Voucher
     */
    kodeVoucher?: string | null;
    /**
     * 
     * @type {Array<Pelanggan>}
     * @memberof Voucher
     */
    pelanggans?: Array<Pelanggan> | null;
}



/**
 * Check if a given object implements the Voucher interface.
 */
export function instanceOfVoucher(value: object): value is Voucher {
    return true;
}

export function VoucherFromJSON(json: any): Voucher {
    return VoucherFromJSONTyped(json, false);
}

export function VoucherFromJSONTyped(json: any, ignoreDiscriminator: boolean): Voucher {
    if (json == null) {
        return json;
    }
    return {
        
        'idVoucher': json['idVoucher'] == null ? undefined : json['idVoucher'],
        'namaVoucher': json['namaVoucher'] == null ? undefined : json['namaVoucher'],
        'statusVoucher': json['statusVoucher'] == null ? undefined : StatusVoucherFromJSON(json['statusVoucher']),
        'tanggalMulai': json['tanggalMulai'] == null ? undefined : (new Date(json['tanggalMulai'])),
        'tanggalAkhir': json['tanggalAkhir'] == null ? undefined : (new Date(json['tanggalAkhir'])),
        'persenVoucher': json['persenVoucher'] == null ? undefined : json['persenVoucher'],
        'kodeVoucher': json['kodeVoucher'] == null ? undefined : json['kodeVoucher'],
        'pelanggans': json['pelanggans'] == null ? undefined : ((json['pelanggans'] as Array<any>).map(PelangganFromJSON)),
    };
}

export function VoucherToJSON(json: any): Voucher {
    return VoucherToJSONTyped(json, false);
}

export function VoucherToJSONTyped(value?: Voucher | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idVoucher': value['idVoucher'],
        'namaVoucher': value['namaVoucher'],
        'statusVoucher': StatusVoucherToJSON(value['statusVoucher']),
        'tanggalMulai': value['tanggalMulai'] == null ? undefined : ((value['tanggalMulai']).toISOString()),
        'tanggalAkhir': value['tanggalAkhir'] == null ? undefined : ((value['tanggalAkhir']).toISOString()),
        'persenVoucher': value['persenVoucher'],
        'kodeVoucher': value['kodeVoucher'],
        'pelanggans': value['pelanggans'] == null ? undefined : ((value['pelanggans'] as Array<any>).map(PelangganToJSON)),
    };
}

