/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CheckVoucherDTO,
  Diskon,
  PostVoucherDTO,
  StatusVoucher,
  Voucher,
} from '../models/index';
import {
    CheckVoucherDTOFromJSON,
    CheckVoucherDTOToJSON,
    DiskonFromJSON,
    DiskonToJSON,
    PostVoucherDTOFromJSON,
    PostVoucherDTOToJSON,
    StatusVoucherFromJSON,
    StatusVoucherToJSON,
    VoucherFromJSON,
    VoucherToJSON,
} from '../models/index';

export interface DiskonCheckVoucherCodeGetRequest {
    code: string;
}

export interface DiskonFilteredGetRequest {
    search?: string;
    status?: StatusVoucher;
    start?: Date;
    end?: Date;
}

export interface DiskonGenericIdDeleteRequest {
    id: number;
}

export interface DiskonGenericIdGetRequest {
    id: number;
}

export interface DiskonGetByCodeCodeGetRequest {
    code: string;
}

export interface DiskonPostRequest {
    postVoucherDTO?: PostVoucherDTO;
}

export interface DiskonPutRequest {
    voucher?: Voucher;
}

/**
 * 
 */
export class DiskonApi extends runtime.BaseAPI {

    /**
     */
    async diskonCheckVoucherCodeGetRaw(requestParameters: DiskonCheckVoucherCodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckVoucherDTO>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling diskonCheckVoucherCodeGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/Diskon/checkVoucher/{code}`.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckVoucherDTOFromJSON(jsonValue));
    }

    /**
     */
    async diskonCheckVoucherCodeGet(requestParameters: DiskonCheckVoucherCodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckVoucherDTO> {
        const response = await this.diskonCheckVoucherCodeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async diskonFilteredGetRaw(requestParameters: DiskonFilteredGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Voucher>>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/Diskon/filtered`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VoucherFromJSON));
    }

    /**
     */
    async diskonFilteredGet(requestParameters: DiskonFilteredGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Voucher>> {
        const response = await this.diskonFilteredGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async diskonGenericIdDeleteRaw(requestParameters: DiskonGenericIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling diskonGenericIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/Diskon/generic/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async diskonGenericIdDelete(requestParameters: DiskonGenericIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.diskonGenericIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async diskonGenericIdGetRaw(requestParameters: DiskonGenericIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Diskon>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling diskonGenericIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/Diskon/generic/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DiskonFromJSON(jsonValue));
    }

    /**
     */
    async diskonGenericIdGet(requestParameters: DiskonGenericIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Diskon> {
        const response = await this.diskonGenericIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async diskonGetActiveGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Voucher>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/Diskon/getActive`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VoucherFromJSON));
    }

    /**
     */
    async diskonGetActiveGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Voucher>> {
        const response = await this.diskonGetActiveGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async diskonGetByCodeCodeGetRaw(requestParameters: DiskonGetByCodeCodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Voucher>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling diskonGetByCodeCodeGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/Diskon/getByCode/{code}`.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VoucherFromJSON(jsonValue));
    }

    /**
     */
    async diskonGetByCodeCodeGet(requestParameters: DiskonGetByCodeCodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Voucher> {
        const response = await this.diskonGetByCodeCodeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async diskonPostRaw(requestParameters: DiskonPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Voucher>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/Diskon`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostVoucherDTOToJSON(requestParameters['postVoucherDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VoucherFromJSON(jsonValue));
    }

    /**
     */
    async diskonPost(requestParameters: DiskonPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Voucher> {
        const response = await this.diskonPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async diskonPutRaw(requestParameters: DiskonPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/Diskon`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: VoucherToJSON(requestParameters['voucher']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async diskonPut(requestParameters: DiskonPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.diskonPutRaw(requestParameters, initOverrides);
    }

}
