/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MotorImage,
  PostMotorImageDTO,
} from '../models/index';
import {
    MotorImageFromJSON,
    MotorImageToJSON,
    PostMotorImageDTOFromJSON,
    PostMotorImageDTOToJSON,
} from '../models/index';

export interface ApiMotorImageIdGetRequest {
    id: number;
}

export interface ApiMotorImagePostRequest {
    postMotorImageDTO?: PostMotorImageDTO;
}

/**
 * 
 */
export class MotorImageApi extends runtime.BaseAPI {

    /**
     */
    async apiMotorImageIdGetRaw(requestParameters: ApiMotorImageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MotorImage>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMotorImageIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/MotorImage/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MotorImageFromJSON(jsonValue));
    }

    /**
     */
    async apiMotorImageIdGet(requestParameters: ApiMotorImageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MotorImage> {
        const response = await this.apiMotorImageIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMotorImagePostRaw(requestParameters: ApiMotorImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MotorImage>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/MotorImage`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostMotorImageDTOToJSON(requestParameters['postMotorImageDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MotorImageFromJSON(jsonValue));
    }

    /**
     */
    async apiMotorImagePost(requestParameters: ApiMotorImagePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MotorImage> {
        const response = await this.apiMotorImagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
