/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Pelanggan,
} from '../models/index';
import {
    PelangganFromJSON,
    PelangganToJSON,
} from '../models/index';

/**
 * 
 */
export class PelangganApi extends runtime.BaseAPI {

    /**
     */
    async pelangganCurrentPelangganGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Pelanggan>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/Pelanggan/currentPelanggan`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PelangganFromJSON(jsonValue));
    }

    /**
     */
    async pelangganCurrentPelangganGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Pelanggan> {
        const response = await this.pelangganCurrentPelangganGetRaw(initOverrides);
        return await response.value();
    }

}
